# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0008_auto_20151021_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['site', 'hostname']},
        ),
        migrations.AlterField(
            model_name='machine',
            name='osmajor',
            field=models.CharField(choices=[(b'5', b'5'), (b'6', b'6'), (b'7', b'7')], default=b'7', max_length=1, verbose_name=b'CentOS Release'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='partition',
            field=models.CharField(choices=[(b'auto', b'Automatic - CentOS will choose for you'), (b'lcogt', b'LCOGT - LCOGT default partition scheme'), (b'prompt', b'Prompt - You will be prompted'), (b'simple', b'Simple - All space in one large partition'), (b'simple-8swap', b'Simple + 8GB swap - All space in one large partition + 8GB swap'), (b'simple-8swap-20var', b'Simple + 8GB swap + 20GB /var - All space in one large partition + 8GB swap + 20GB /var'), (b'custom', b'Custom - Custom partition scheme (advanced!)')], default=b'auto', max_length=128, verbose_name=b'Partition Scheme'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='site',
            field=models.CharField(choices=[(b'bpl', b'BPL - Santa Barbara Back Parking Lot'), (b'coj', b'COJ - Siding Spring, Australia'), (b'cpt', b'CPT - SAAO Sutherland, South Africa'), (b'elp', b'ELP - McDonald Observatory, Texas'), (b'lpl', b'LPL - Liverpool, England'), (b'lsc', b'LSC - Cerro Tololo, Chile'), (b'mfg', b'MFG - Manufacturing'), (b'ngq', b'NGQ - Tibet'), (b'ogg', b'OGG - Haleakala, Hawaii'), (b'ptr', b'PTR - Photon Ranch, California'), (b'sba', b'SBA - Santa Barbara, California'), (b'sqa', b'SQA - Sedgwick Reserve, California'), (b'tlv', b'TLV - Tel Aviv, Israel'), (b'tfn', b'TFN - Tenerife'), (b'wtf', b'WTF - Warehouse Test Facility')], default=b'sba', max_length=3, verbose_name=b'LCOGT Site'),
        ),
    ]
