# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0009_auto_20161019_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name=b'Timestamp')),
                ('ipaddress', models.GenericIPAddressField(protocol='ipv4', verbose_name=b'IP Address')),
                ('url', models.CharField(max_length=64, verbose_name=b'Request')),
                ('success', models.BooleanField(default=False, verbose_name=b'Success')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
