# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0011_auto_20161130_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='site',
            field=models.CharField(choices=[(b'bpl', b'BPL - Santa Barbara Back Parking Lot'), (b'coj', b'COJ - Siding Spring, Australia'), (b'cpt', b'CPT - SAAO Sutherland, South Africa'), (b'elp', b'ELP - McDonald Observatory, Texas'), (b'lpl', b'LPL - Liverpool, England'), (b'lsc', b'LSC - Cerro Tololo, Chile'), (b'mfg', b'MFG - Manufacturing'), (b'ngq', b'NGQ - Tibet'), (b'ogg', b'OGG - Haleakala, Hawaii'), (b'ptr', b'PTR - Photon Ranch, California'), (b'sba', b'SBA - Santa Barbara, California'), (b'sci', b'SCI - Science Domain, Santa Barbara, California'), (b'sqa', b'SQA - Sedgwick Reserve, California'), (b'tlv', b'TLV - Tel Aviv, Israel'), (b'tfn', b'TFN - Tenerife'), (b'wtf', b'WTF - Warehouse Test Facility')], default=b'sba', max_length=3, verbose_name=b'LCOGT Site'),
        ),
    ]
