# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-27 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0012_auto_20170213_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='nameserver',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='netmask',
        ),
    ]
