# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-04 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0013_auto_20170427_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='use_local_mirror',
        ),
        migrations.AddField(
            model_name='machine',
            name='packagemirror',
            field=models.CharField(default=b'', max_length=256, verbose_name=b'Package Mirror URL'),
        ),
    ]
