# Generated by Django 2.0.2 on 2019-05-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0016_auto_20190524_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='puppetmaster',
        ),
    ]
