# Generated by Django 2.0.2 on 2019-05-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0017_remove_machine_puppetmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='packagemirror',
        ),
    ]
