# Generated by Django 2.0.2 on 2019-05-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0018_remove_machine_packagemirror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='boot_mode',
            field=models.CharField(choices=[('local', 'Boot from local disk'), ('rebuild', 'Rebuild at next boot'), ('rebuildalt', 'Rebuild at next boot (use alternate package mirror)'), ('rescue', 'Rescue at next boot')], default='rebuild', max_length=16, verbose_name='Boot mode'),
        ),
    ]
