# Generated by Django 2.2.7 on 2019-11-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0019_auto_20190524_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='osmajor',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='7', max_length=1, verbose_name='CentOS Release'),
        ),
    ]
