# Generated by Django 2.2.10 on 2020-02-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0020_auto_20191115_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='ostype',
            field=models.CharField(choices=[('centos', 'CentOS'), ('proxmox', 'Proxmox VE')], default='centos', max_length=32, verbose_name='Operating System Type'),
        ),
        migrations.AddField(
            model_name='machine',
            name='osversion',
            field=models.CharField(default='7', max_length=8, verbose_name='Operating System Version'),
        ),
    ]
