# Generated by Django 2.2.10 on 2020-02-19 23:26

from django.db import migrations

def copy_osmajor_to_osversion(apps, schema_editor):
    '''
    Copy the osmajor database field into the osversion database field. This
    will allow us to seamlessly migrate the first field name to the second.

    https://docs.djangoproject.com/en/3.0/topics/migrations/#data-migrations
    '''
    Machine = apps.get_model('machineconfig', 'Machine')
    for machine in Machine.objects.all():
        machine.osversion = str(machine.osmajor)
        machine.save()

class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0021_auto_20200219_2324'),
    ]

    operations = [
        migrations.RunPython(copy_osmajor_to_osversion),
    ]
