# Generated by Django 2.2.10 on 2020-02-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0022_auto_20200219_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='osmajor',
        ),
    ]
