# Generated by Django 3.0.4 on 2020-03-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0023_remove_machine_osmajor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='LCO Site Code')),
                ('shortdescription', models.CharField(max_length=128, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
    ]
