# Generated by Django 3.0.4 on 2020-03-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0026_auto_20200319_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='gateway',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', verbose_name='Default Gateway'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='netmask',
            field=models.GenericIPAddressField(default='255.255.0.0', protocol='ipv4', verbose_name='Network Netmask'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='network',
            field=models.GenericIPAddressField(default='127.0.0.1', protocol='ipv4', verbose_name='Network IP Address'),
            preserve_default=False,
        ),
    ]
