# Generated by Django 3.0.4 on 2020-03-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0027_auto_20200320_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='network',
            new_name='networkip',
        ),
        migrations.RemoveField(
            model_name='site',
            name='netmask',
        ),
        migrations.AddField(
            model_name='site',
            name='networkcidr',
            field=models.SmallIntegerField(default=16, verbose_name='Network CIDR'),
        ),
    ]
