# Generated by Django 3.0.5 on 2020-05-09 03:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0029_auto_20200509_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='nameserver',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(protocol='ipv4', verbose_name='Nameserver'), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
