# Generated by Django 3.0.5 on 2020-05-09 03:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0030_auto_20200509_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterfaceconfiguration',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Hostname Alias'), default=list, size=None),
        ),
    ]
