# Generated by Django 3.0.5 on 2020-05-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0031_auto_20200509_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppetmachine',
            name='id',
        ),
        migrations.AlterField(
            model_name='puppetmachine',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='machineconfig.NetworkDevice', verbose_name='Network Device'),
        ),
    ]
