# Generated by Django 3.0.5 on 2020-05-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0032_auto_20200509_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='image',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='', verbose_name='Device Image'),
        ),
    ]
