# Generated by Django 3.0.5 on 2020-05-22 05:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0034_auto_20200509_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterfaceconfiguration',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, verbose_name='Hostname Alias'), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='networkinterfaceconfiguration',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', verbose_name='IP Address'),
        ),
    ]
