# Generated by Django 3.0.5 on 2020-05-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0035_auto_20200522_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterfaceconfiguration',
            name='ipaddress',
            field=models.GenericIPAddressField(default='255.255.255.255', protocol='ipv4', verbose_name='IP Address'),
        ),
    ]
