# Generated by Django 3.0.5 on 2020-05-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0036_auto_20200522_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterfaceconfiguration',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', verbose_name='IP Address'),
        ),
    ]
