# Generated by Django 3.0.5 on 2020-05-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0038_auto_20200523_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterfaceconfiguration',
            name='hostname',
            field=models.CharField(max_length=256, unique=True, verbose_name='Hostname'),
        ),
    ]
