# Generated by Django 3.0.5 on 2020-06-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0039_auto_20200524_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppetmachine',
            name='boot_mode',
            field=models.CharField(choices=[('local', 'Boot from local disk'), ('rebuild', 'Rebuild at next boot'), ('rebuildalt', 'Rebuild at next boot (use alternate package mirror)'), ('rescue', 'Rescue at next boot')], default='local', max_length=32, verbose_name='Boot Mode'),
        ),
        migrations.AlterField(
            model_name='puppetmachine',
            name='lastboot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puppetmachine',
            name='partitionscheme',
            field=models.CharField(choices=[('auto', 'Automatic - CentOS will choose for you'), ('docknode', 'Docker node standard partition scheme'), ('lcogt', 'LCOGT - LCOGT default partition scheme'), ('prompt', 'Prompt - You will be prompted'), ('pubsubdb', 'PubsubDB - PubsubDB standard partition scheme'), ('simple', 'Simple - All space in one large partition'), ('simple-8swap', 'Simple + 8GB swap - All space in one large partition + 8GB swap'), ('simple-8swap-20var', 'Simple + 8GB swap + 20GB /var - All space in one large partition + 8GB swap + 20GB /var'), ('custom', 'Custom - Custom partition scheme (advanced!)')], default='simple', max_length=32, verbose_name='Partition Scheme'),
        ),
    ]
