# Generated by Django 3.0.5 on 2020-07-24 21:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0040_auto_20200602_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterfaceconfiguration',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, unique=True, verbose_name='Hostname Alias'), blank=True, default=list, size=None),
        ),
    ]
