# Generated by Django 3.0.5 on 2020-07-24 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0042_auto_20200724_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkinterfaceconfiguration',
            name='aliases',
        ),
        migrations.RemoveField(
            model_name='networkinterfaceconfiguration',
            name='hostname',
        ),
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=256, unique=True, verbose_name='Hostname')),
                ('alias', models.BooleanField(default=False, verbose_name='Alias')),
                ('networkinterfaceconfiguration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineconfig.NetworkInterfaceConfiguration')),
            ],
        ),
    ]
