# Generated by Django 3.0.5 on 2020-07-24 23:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0043_auto_20200724_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterfaceconfiguration',
            name='hostnames2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, unique=True, verbose_name='Hostname'), blank=True, default=list, size=None),
        ),
    ]
