# Generated by Django 3.0.5 on 2020-07-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0044_networkinterfaceconfiguration_hostnames2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkinterfaceconfiguration',
            name='hostnames2',
        ),
    ]
