# Generated by Django 3.0.5 on 2020-07-24 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0045_remove_networkinterfaceconfiguration_hostnames2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostname',
            name='alias',
        ),
        migrations.AddField(
            model_name='hostname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 24, 23, 56, 13, 480862)),
            preserve_default=False,
        ),
    ]
