# Generated by Django 3.0.5 on 2020-08-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0047_site_elevation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='LCO Site Code'),
        ),
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(max_length=64, unique=True, verbose_name='Network Domain'),
        ),
        migrations.AlterField(
            model_name='site',
            name='networkip',
            field=models.GenericIPAddressField(protocol='ipv4', unique=True, verbose_name='Network IP Address'),
        ),
    ]
