# Generated by Django 3.0.9 on 2020-08-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0048_auto_20200802_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppetmachine',
            name='lastbuild_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, max_length=131072, verbose_name='Description'),
        ),
    ]
