# Generated by Django 3.0.9 on 2020-08-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0049_auto_20200806_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='information',
            field=models.TextField(blank=True, max_length=131072),
        ),
    ]
