# Generated by Django 3.0.9 on 2020-08-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0050_auto_20200807_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='timezone',
            field=models.CharField(default='Etc/UTC', max_length=64, verbose_name='Timezone'),
        ),
    ]
