# Generated by Django 3.0.9 on 2020-08-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0051_site_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='restart_time',
            field=models.TimeField(default='00:00:00', verbose_name='Restart Time'),
        ),
    ]
