# Generated by Django 3.1.1 on 2020-09-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0052_site_restart_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='Device Image'),
        ),
    ]
