# Generated by Django 3.1.1 on 2020-09-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0053_auto_20200909_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnrecognizedPXEDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, verbose_name='MAC Address')),
                ('ipaddress', models.GenericIPAddressField(protocol='ipv4', verbose_name='IP Address')),
            ],
        ),
    ]
