# Generated by Django 3.1.1 on 2020-09-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0054_unrecognizedpxedevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='unrecognizedpxedevice',
            name='data',
            field=models.TextField(blank=True, max_length=131072, verbose_name='Data'),
        ),
    ]
