# Generated by Django 3.1.1 on 2020-09-11 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0056_unrecognizedpxedevice_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppetmachine',
            name='lastboot_at',
        ),
        migrations.RemoveField(
            model_name='puppetmachine',
            name='lastbuild_at',
        ),
        migrations.CreateModel(
            name='BuildHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=32, verbose_name='Status')),
                ('puppetmachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineconfig.puppetmachine')),
            ],
        ),
        migrations.CreateModel(
            name='BootHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boot_mode', models.CharField(choices=[('local', 'Boot from local disk'), ('rebuild', 'Rebuild at next boot'), ('rebuildalt', 'Rebuild at next boot (use alternate package mirror)'), ('rescue', 'Rescue at next boot')], default='local', max_length=32, verbose_name='Boot Mode')),
                ('puppetmachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineconfig.puppetmachine')),
            ],
        ),
    ]
