# Generated by Django 3.1.1 on 2020-09-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0057_auto_20200911_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='mirrorbase',
            field=models.URLField(default='http://packagerepo.lco.gtn/repos', max_length=1024, verbose_name='Primary Package Mirror'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='mirrorbasealt',
            field=models.URLField(default='http://packagerepo.lco.gtn/repos', max_length=1024, verbose_name='Alternate Package Mirror'),
            preserve_default=False,
        ),
    ]
