# Generated by Django 3.1.1 on 2020-09-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0058_auto_20200915_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='external_gateway',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', verbose_name='External Next-Hop Upstream Gateway'),
        ),
        migrations.AddField(
            model_name='site',
            name='external_networkcidr',
            field=models.SmallIntegerField(default=32, verbose_name='External Network CIDR'),
        ),
        migrations.AddField(
            model_name='site',
            name='external_networkip',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', verbose_name='External Network IP Address'),
        ),
    ]
