# Generated by Django 3.1.1 on 2020-09-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0059_auto_20200922_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='external_gateway',
        ),
        migrations.AddField(
            model_name='site',
            name='external_borderexternal',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', verbose_name='External Border Router IP Address'),
        ),
        migrations.AddField(
            model_name='site',
            name='external_borderuplink',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', verbose_name='External Border Router Next-Hop Uplink IP Address'),
        ),
        migrations.AlterField(
            model_name='site',
            name='external_networkcidr',
            field=models.SmallIntegerField(default=30, verbose_name='External Network CIDR'),
        ),
    ]
