# Generated by Django 3.1.1 on 2020-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0060_auto_20200922_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='external_sitetositevpnip',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', verbose_name='IPSec VPN Backend IP Address'),
        ),
    ]
