# Generated by Django 3.1.1 on 2020-09-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0061_site_external_sitetositevpnip'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTPServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=1024, verbose_name='NTP Server Hostname/IP Address')),
                ('options', models.CharField(blank=True, default='', max_length=1024, verbose_name='NTP Configuration Options')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineconfig.site')),
            ],
        ),
    ]
