# Generated by Django 3.1.1 on 2020-09-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0062_ntpserver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ntpserver',
            options={'ordering': ['created_at']},
        ),
    ]
