# Generated by Django 3.1.1 on 2020-09-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0063_auto_20200923_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='last_boot_at',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='updated_at',
        ),
    ]
