# Generated by Django 3.1.1 on 2020-09-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0064_auto_20200923_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='fmxurl',
            field=models.URLField(blank=True, default='', max_length=4096, verbose_name='FMX URL'),
        ),
    ]
