# Generated by Django 3.1.1 on 2020-10-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0065_networkdevice_fmxurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppetmachine',
            name='operatingsystem',
            field=models.CharField(choices=[('centos-5-i386', 'CentOS 5 i386'), ('centos-5-x86_64', 'CentOS 5 x86_64'), ('centos-6-i386', 'CentOS 6 i686'), ('centos-6-x86_64', 'CentOS 6 x86_64'), ('centos-7-x86_64', 'CentOS 7 x86_64'), ('centos-8-x86_64', 'CentOS 8 x86_64'), ('proxmox-61-x86_64', 'Proxmox VE 6.1 x86_64')], default='centos-7-x86_64', max_length=256, verbose_name='Operating System'),
        ),
    ]
