# Generated by Django 3.1.1 on 2020-10-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0067_auto_20201002_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppetmachine',
            name='arch',
        ),
        migrations.RemoveField(
            model_name='puppetmachine',
            name='ostype',
        ),
        migrations.RemoveField(
            model_name='puppetmachine',
            name='osversion',
        ),
    ]
