# Generated by Django 3.1.1 on 2020-10-05 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0068_auto_20201002_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('networkdevice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='machineconfig.networkdevice', verbose_name='Network Device')),
                ('adminurl', models.URLField(blank=True, max_length=1024, verbose_name='Webcam Administration Interface URL')),
                ('imageurl', models.URLField(blank=True, max_length=1024, verbose_name='Webcam Image Fetch URL')),
                ('enabled', models.BooleanField(default=True, verbose_name='Is this Webcam enabled?')),
                ('public', models.BooleanField(default=False, verbose_name='Is this Webcam available to the Public Internet?')),
                ('dome', models.BooleanField(default=False, verbose_name='Is this Webcam a Dome Camera?')),
            ],
        ),
    ]
