# Generated by Django 3.1.1 on 2020-10-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0069_webcam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcam',
            old_name='dome',
            new_name='is_dome',
        ),
        migrations.RenameField(
            model_name='webcam',
            old_name='enabled',
            new_name='is_enabled',
        ),
        migrations.RenameField(
            model_name='webcam',
            old_name='public',
            new_name='is_public',
        ),
    ]
