# Generated by Django 2.2.14 on 2020-07-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineconfig', '0023_remove_machine_osmajor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='site',
            field=models.CharField(choices=[('bpl', 'BPL - Santa Barbara Back Parking Lot'), ('coj', 'COJ - Siding Spring, Australia'), ('cpt', 'CPT - SAAO Sutherland, South Africa'), ('elp', 'ELP - McDonald Observatory, Texas'), ('ljg', 'LJG - Lijiang, Yunnan, China 丽江 云南'), ('lpl', 'LPL - Liverpool, England'), ('lsc', 'LSC - Cerro Tololo, Chile'), ('mfg', 'MFG - Manufacturing'), ('ngq', 'NGQ - Tibet'), ('ogg', 'OGG - Haleakala, Hawaii'), ('ptr', 'PTR - Photon Ranch, California'), ('sba', 'SBA - Santa Barbara, California'), ('sci', 'SCI - Science Domain, Santa Barbara, California'), ('sqa', 'SQA - Sedgwick Reserve, California'), ('tlv', 'TLV - Tel Aviv, Israel'), ('tfn', 'TFN - Tenerife'), ('wer', 'WER - Wayne Rosing'), ('wtf', 'WTF - Warehouse Test Facility')], default='sba', max_length=3, verbose_name='LCOGT Site'),
        ),
    ]
